// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6mi6POHnw6CmzBoBtMUVdiKxPlTdMUYM',
    appId: '1:705832394342:web:ea0c1d994fd1f1582197a7',
    messagingSenderId: '705832394342',
    projectId: 'pruebasemisenior',
    authDomain: 'pruebasemisenior.firebaseapp.com',
    storageBucket: 'pruebasemisenior.firebasestorage.app',
    measurementId: 'G-MGEFRR07C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0s66Rtnku0Zw3C_jxOKBlwM0hugL1yUQ',
    appId: '1:705832394342:android:cc42e41320bf9fd12197a7',
    messagingSenderId: '705832394342',
    projectId: 'pruebasemisenior',
    storageBucket: 'pruebasemisenior.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWGyTvCEctq-BOAVTWdMr6oqoLTyL_YsI',
    appId: '1:705832394342:ios:1ca9cac8b9e965ff2197a7',
    messagingSenderId: '705832394342',
    projectId: 'pruebasemisenior',
    storageBucket: 'pruebasemisenior.firebasestorage.app',
    iosBundleId: 'com.example.doublevpartners',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWGyTvCEctq-BOAVTWdMr6oqoLTyL_YsI',
    appId: '1:705832394342:ios:1ca9cac8b9e965ff2197a7',
    messagingSenderId: '705832394342',
    projectId: 'pruebasemisenior',
    storageBucket: 'pruebasemisenior.firebasestorage.app',
    iosBundleId: 'com.example.doublevpartners',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6mi6POHnw6CmzBoBtMUVdiKxPlTdMUYM',
    appId: '1:705832394342:web:4e5b66c9ecb065ed2197a7',
    messagingSenderId: '705832394342',
    projectId: 'pruebasemisenior',
    authDomain: 'pruebasemisenior.firebaseapp.com',
    storageBucket: 'pruebasemisenior.firebasestorage.app',
    measurementId: 'G-E7TRL70SW6',
  );
}
